### ISSUE TITLE
useless popup during password entry

### ISSUE THREAD

**Issue by 532910** [DDoSolitary/OkcAgent#11]
![image](https://user-images.githubusercontent.com/14617699/88489917-54a46b80-cfa0-11ea-9a68-91bd47ce40d8.png)

This is the latest dev build

**Comment by DDoSolitary** [comment]
It is not useless technically. In order to call the API provided by OpenKeychain, I have to use the `startIntentSenderForResult` method, which is only available for activities but not services. As a result, I have to start an activity (which shows this popup) to call this method.

**Comment by 532910** [comment]
But current F-Droid version doesn't pop-up.

**Comment by DDoSolitary** [comment]
It does, but the dialog might be hidden by the password prompt window because older versions has a bit smaller dialog width. I forced the dialog to have 100% width of the screen in a recent commit (e93605ccd07e1f404c4b5579754ef8417a6b0382) because I found that the error dialog width is unreasonably small when shown from the background service.

If you think the dialog in annoying I can make its width a bit smaller (e.g. 90% of screen width) so that it will still be covered by the password prompt.

**Comment by 532910** [comment]
Not annoying but ugly and distrustful, like I entering a password for something else, that I even can't see.

I think there are two solutions:
1. make it smaller than a password popup.
2. make it larger, so it will be clear what is it.

**Comment by DDoSolitary** [comment]
I think I'll just revert to the old dialog width. I just realized that showing dialogs from background is also not supported on Android 10, so I decide to use notifications to show errors when in background. Then the change in dialog width will be no longer needed.

**Comment by 532910** [comment]
ack
