### ISSUE TITLE
tapping the notification for authorization

### ISSUE THREAD

**Issue by 532910** [DDoSolitary/OkcAgent#13]
There was a change in behaviour during the development: it was required or not to tap notification to make an OpenKeychain request.

1. I believe this is an excessive step.
2. It's hard to understand that new notification was thrown and an active user action is required.

If there are some reasons for this behaviour it should be configurable.

**Comment by DDoSolitary** [comment]
Yes I understand it's a bit annoying, but it is something required by Android 10.

Previously, this app works as a service to handle requests from Termux, and starts an activity when user interaction is required. However, since Android 10, [apps are no longer allowed to start activities directly from background](https://developer.android.com/guide/components/activities/background-starts). So the previous approach no longer works and I just implemented the recommended workaround: use a notification to request user interaction.

> It's hard to understand that new notification was thrown and an active user action is required.

The notification is set to have a high priority so it should be displayed as a heads-up notification by default, which is easily to notice.

> If there are some reasons for this behaviour it should be configurable.

No, it's not a good idea. It is simply wrong to keep using the old behavior due to the aforementioned change in Android 10.

**Comment by 532910** [comment]
Clear, thank you for explanation!

I set `Override Do Not Disturb` for `Authorizations request` notification and live become easier.

**Comment by TychoSchenkeveld** [comment]
Thanks @DDoSolitary !

It works well now without the notification! I now get the prompt from OKC immediately, asking me to tap the Yubikey. This is just what I was looking for.

Thanks so much! Will this come into the production version too?

**Comment by DDoSolitary** [comment]
@TychoSchenkeveld Yes, this change will be available in the next release.
