### ISSUE TITLE
F-Droid can't build - Firebase is not FOSS

### ISSUE THREAD

**Issue by licaon-kter** [DDoSolitary/OkcAgent#16]
Ref: https://f-droid.org/wiki/index.php?title=org.ddosolitary.okcagent/lastbuild_5&oldid=274827

Ref: https://github.com/DDoSolitary/OkcAgent/commit/5dd1bfaf345719f16d020321f25e667fde5c0c7c

Ref: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7266

**Comment by DDoSolitary** [comment]
Well, I didn't even know that Firebase is not fully FOSS because there's a [firebase/firebase-android-sdk](https://github.com/firebase/firebase-android-sdk) on GitHub. I just checked it again and found out that it only contains some part of the SDK.

Could you please some suggestions on alternatives to Firebase? I'm not going to use paid products or self-hosted solutions because I'm unable to afford that. Currently I'm considering Microsoft App Center, which seems to have a fully open source SDK: https://github.com/microsoft/appcenter-sdk-android

**Comment by licaon-kter** [comment]
MS App Center might be, but careful not to include the Push part.

Bugsnag or ACRA or Sentry, I guess?

**Comment by DDoSolitary** [comment]
Thanks a lot for your suggestion. I just migrated to Bugsnag and removed all usage of Firebase.

**Comment by licaon-kter** [comment]
Don't forget to add a setting to toggle this, maybe make it off by default (aka opt-in) else we'll need to add `AntiFeature: Tracking`

Also, add same sort of Privacy Policy to explain what data is transmitted, to whom, etc etc

**Comment by DDoSolitary** [comment]
The new release (v0.2.3) has switched to Bugsnag and allows users to enable/disable automatic error reporting. It will also ask if error reporting should be enabled on first launch.
