### ISSUE TITLE
Notification hangs "Serving SSH agent requests..."

### ISSUE THREAD

**Issue by gthar** [DDoSolitary/OkcAgent#20]
app version: 0.2.0
download source: F-Droid

When I try to SSH, I get the OkcAgent notification with "SSH Agent Service - Serving SSH agent requests...", but it just hangs in there indefinitely and OpenKeychain never shows up.
I'm not sure where to find more logs to troubleshoot this.

I am using GrapheneOS (Android 10), in case that's relevant

**Comment by DDoSolitary** [comment]
Unfortunately, v0.2.0 is not compatible with Android 10. While support for Android 10 has been added in newer releases, they're not yet available on F-Droid (#16). Hopefully this will be fixed in the next release. For now I suggest use the apk files from [GitHub Releases](https://github.com/DDoSolitary/OkcAgent/releases), though you may have to uninstall the existing one first because it is signed with a different key.

**Comment by gthar** [comment]
Thanks! It works great now.
My bad for not trying it with the newest version before opening the issue.
