### ISSUE TITLE
Permanent (unclearable) notification

### ISSUE THREAD

**Issue by 532910** [DDoSolitary/OkcAgent#4]
![image](https://user-images.githubusercontent.com/14617699/65831517-1fb58280-e2c3-11e9-8588-39df22ccf555.png)

I can't clear it. I don't know how to reproduce it.

okcagent version r47

**Comment by 532910** [comment]
As far as i see it happens when I already ssh'ed somewhere and unlocked OpenKeychain (in other words not on the first OkcAgent usage). Sometimes on some agent access (by ssh or sudo as I use pam_ssh_agent_auth) OkcAgent hangs and permanent notification sticks forever.

If I retry the same ssh or sudo command it works correctly.

**Comment by DDoSolitary** [comment]
Such hanging is pretty hard to reproduce and debug. I've encountered this before, but I was unable to reproduce it when I actually tried to fix it. So for now I decided to add a button to the notification to allow terminating the service manually.

**Comment by 532910** [comment]
This is still reproducible quite often with F-Droid version.
Please reopen.

**Comment by DDoSolitary** [comment]
@532910 I just tried about ten times again and still unable to reproduce it. However, I just remembered that I pushed a commit (6b5c0831e120e1bdc1cc5b7c466c8418efc4478e) several hours earlier which fixes a random hanging issue which seems like to be what you described. (I didn't notice earlier that it might be related because I made the fix when working on GPG part of the code and this issue is about the SSH agent.) Could you please try the latest dev release and see if you can still reproduce the bug?

**Comment by 532910** [comment]
Looks like this is fixed in the latest build, I'll reopen if I got it again.
